package com.bx.ultimateDonutSmp.models;

public enum EconomyReason {
    ADMIN_ADD,
    ADMIN_REMOVE,
    ADMIN_SET,
    PLAYER_PAY,
    SHOP_PURCHASE,
    SELL_PAYOUT,
    AUCTION_LISTING_FEE,
    AUCTION_PURCHASE,
    AUCTION_REFUND,
    AUCTION_CLAIM,
    ORDER_CREATE_ESCROW,
    ORDER_CREATE_FEE,
    ORDER_DELIVERY_PAYOUT,
    ORDER_REFUND,
    BOUNTY_PLACE,
    BOUNTY_REWARD,
    BILLFORD_REWARD,
    AMETHYST_SELL
}
